services:
  - type: web
    name: laravelHostCrud
    env: php
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://laravelhostcrud.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12802173
      - key: DB_USERNAME
        value: sql12802173
      - key: DB_PASSWORD
        value: vlvL7mTQSV